services:

  as-postgres:
    image: postgres:latest
    container_name: postgres_authserver
    restart: always
    environment:
      POSTGRES_DB: authserver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data

  as-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_authserver
    restart: always
    depends_on:
      - as-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - .data/pgadmin:/var/lib/pgadmin

networks:
  default:
    name: authserver-network
    external: true
