server:
  port: 9090
spring:
  application:
    name: auth-server
  redis:
    host: localhost
    port: 6379

jwt:
  encryptor:
    password: test
    salt: 626F6F746966756C
  key:
    id: 'configured-f57f-46a2-b502-8a24c308be7f'
    public: classpath:private-key.pem
    private: classpath:public-key.pem

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
