server:
  port: 9000
spring:
  application:
    name: auth-server
  security:
    oauth2:
      clients:
        login-client:
          client-id: login-client
          client-secret: password
          authorized-grant-types: authorization_code
          redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
          scope: openid,profile
  datasource:
    url: jdbc:postgresql://localhost:5434/authserver
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  redis:
#    host: localhost
#    port: 6379


jwt:
  encryptor:
    password: password
  key:
    public: classpath:app.pub
    private: classpath:app.key

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
