spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          login-client:
            client-id: login-client
            client-secret: password
            scope: read:user
            provider:
              spring:
                authorization-uri: http://localhost:9000/oauth2/authorize
                token-uri: http://localhost:9000/oauth2/token
                jwk-set-uri: http://localhost:9000/oauth2/jwks

